name: 'Run tests'

on:
  push:
  workflow_dispatch:

jobs:
  test:
    name: Test ${{ matrix.project }}
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        project: [plumber, external-service-interaction]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup system dependencies
        run: |
          packages=(
            # List each package on a separate line.
            libcurl4-openssl-dev
            libsodium-dev
          )
          sudo apt-get update
          sudo apt-get install --yes "${packages[@]}"

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          working-directory: ${{ matrix.project }}

      - name: Setup R dependencies
        uses: r-lib/actions/setup-renv@v2
        with:
          working-directory: ${{ matrix.project }}

      - name: Test
        run: |
          cd ${{ matrix.project }}
          Rscript -e 'testthat::test_local()'
